### ISSUE TITLE
Do not use $_SESSION directly outside of the Session Class

### ISSUE THREAD

**Issue by JPustkuchen** [fabianwennink/IconCaptcha-Plugin-jQuery-PHP#22]
As the title says :)

https://github.com/fabianwennink/IconCaptcha-Plugin-jQuery-PHP/blob/290afc611d102b720db6588ac2d0cfa0d7861db7/src/Token/Token.php#L65

**Comment by fabianwennink** [comment]
Referenced in other issue (15), closed to keep the discussion in just that issue.
