### ISSUE TITLE
Make session data reliable / explicit

### ISSUE THREAD

**Issue by JPustkuchen** [fabianwennink/IconCaptcha-Plugin-jQuery-PHP#24]
The SessionInterface and Session class idea is great!

Still it needs some work to really fulfil the requirements of an interface, which is a contract. This contract isn't detailed enough here, yet :)

What's missing is the reliability on the session values / keys. 

**TL;DR:** The magic methods have to be removed and replaced by either
a) a SessionData [value object](https://lessthan12ms.com/value-objects-in-php.html) containing all used values as properties (think this might be a bit better)
or
b) explicit getters and setters for these values on the Session object.

The problem is otherwise that the Interface can never tell, which values / keys exist reliably for code using the session.

You can see these implicit keys here:
```
    /**
     * This will clear the set hashes, and reset the icon
     * request counter and last clicked icon.
     */
    public function clear()
    {
        $this->session['icons'] = [];
        $this->session['iconIds'] = [];
        $this->session['correctId'] = 0;
        $this->session['requested'] = false;
        $this->session['completed'] = false;
        $this->session['attempts'] = 0;
    }

    /**
     * Destroys the captcha session.
     */
    public function destroy()
    {
        unset($_SESSION[$this->key][$this->id]);
    }

    /**
     * Loads the captcha's session data based on the earlier set captcha identifier.
     */
    public function load()
    {
        if (self::exists($this->key, $this->id)) {
            $this->session = $_SESSION[$this->key][$this->id];
        } else {
            $this->session = [
                'icons' => [], // The positions of the icon on the generated image.
                'iconIds' => [], // List of used icon IDs.
                'correctId' => 0, // The icon ID of the correct answer/icon.
                'mode' => 'light', // The name of the theme used by the captcha instance.
                'requested' => false, // If the captcha image has been requested yet.
                'completed' => false, // If the captcha was completed (correct icon selected) or not.
                'attempts' => 0, // The number of times an incorrect answer was given.
            ];
        }
    }
```

**Comment by fabianwennink** [comment]
@JPustkuchen Please do not open new issues regarding the same topic as #15, instead add a comment on that issue.

**Comment by JPustkuchen** [comment]
@fabianwennink thanks, okay! :)

I thought that might be too much in one issue. 

Idea: Shouldn't we instead use milestones and labels for issues perhaps to target a release / branch and still separate issues?

**Comment by fabianwennink** [comment]
Referenced in other issue (15), closed to keep the discussion in just that issue.
