### ISSUE TITLE
Document building custom challenges

### ISSUE THREAD

**Issue by yakyouk** [fabianwennink/IconCaptcha-Plugin-jQuery-PHP#25]
Hello, thank you for such a great functionality!
If this is already a possibility, it would be great to have examples on building custom challenges in addition to the built-in one, and possibly display a challenge at random to the user.

**Comment by fabianwennink** [comment]
Hi @yakyouk. IconCaptcha does not support building custom challenges at this moment. The changes made in the upcoming version (v4) will make such a feature easier to implement, but I'm not sure when/if this will actually be a supported in the future. I will add this feature request to the backlog of this project.
