### ISSUE TITLE
Constants in captcha.class.php restrict customisation

### ISSUE THREAD

**Issue by bazalt** [fabianwennink/IconCaptcha-Plugin-jQuery-PHP#30]
Hi,

I tried to implement IconCaptcha with a custom set of **163** icons, until I realised that icons sets MUST count **180** elements:
https://github.com/fabianwennink/IconCaptcha-Plugin-jQuery-PHP/blob/1ebdf2e2f3cfe37bbfd5de8484c96c9685ade21f/src/captcha.class.php#L23

Same issue may arise with `CAPTCHA_IMAGE_SIZE`, `SESSION_NAME` (which could be concerned by [this issue](https://github.com/fabianwennink/IconCaptcha-Plugin-Front-End/issues/6) too), or other constants.

In my case, I bypassed this restriction by filling-up missing icons with the ones included in your library, and it's working fine.
Anyway, is there any plan to allow overriding these constants ?

Thanks.

**Comment by fabianwennink** [comment]
Hi @bazalt. Yes, having the icon amount as a fixed constant wasn't the smartest thing to do - that's my bad... In the upcoming major version (v4), this has been resolved by adding the icon count as an [option in the configuration](https://github.com/fabianwennink/IconCaptcha-Plugin-jQuery-PHP/blob/develop/examples/captcha-config.php#L29). I'm thinking about adding this option to the current version (v3) as well. Doing the same for the session name would be an option, but I'm not sure if anyone is having an issue with this at the moment, as the session name is 'iconcaptcha'. Regardless, this is still something I could implement.

Regarding the fixed image size, this is done as the calculations for icon placement and size are based around this size. Making this variable, would break the captcha in both the backend, as well as the widget itself.

**Comment by fabianwennink** [comment]
The icon amount option has now been added to the latest release [v3.1.2](https://github.com/fabianwennink/IconCaptcha-Plugin-jQuery-PHP/releases/tag/3.1.2). The constant has been removed as well.

**Comment by bazalt** [comment]
Excellent, thank you!
