### ISSUE TITLE
a status of 403 () from captcha-request.php

### ISSUE THREAD

**Issue by hansal0** [fabianwennink/IconCaptcha-Plugin-jQuery-PHP#4]
i'm using Iconcaptcha-plugin from time , and it was working well.
but suddenly after i made minify for javascript for the site but **not for the capcha.**
i face this issue now for the first time from the captcha and there are not any images.
but when click on the captha on images place , the captcha load correctly and works fine .

**Comment by fabianwennink** [comment]
Could you please clarify what problems you are facing? Did the captcha stop working after you minified the Javascript code? If so, the minifier most likely broke the code somewhere.

**Comment by fabianwennink** [comment]
Closed due to inactivity.
