### ISSUE TITLE
Same image

### ISSUE THREAD

**Issue by Cage31** [fabianwennink/IconCaptcha-Plugin-jQuery-PHP#8]
Hello,

always good job, and another question :-)
Some time iconCaptcha don't propose a unique wrong image.
I would like to have only one wrong image. Is -it possible ?

Thanks for you work
<img width="355" alt="Capture d’écran 2021-10-19 à 00 33 37" src="https://user-images.githubusercontent.com/2852664/137816007-3498a6af-1057-4c79-9821-3cf9effdbeaf.png">
.

**Comment by fabianwennink** [comment]
With IconCaptcha you are supposed to select the icon which appears the least amount of times. In this case there are 4 diamonds and 1 RV/camping car, which makes the RV/camping car the icon that you must select - as it appears only once (1 out of 5).
